language: fr
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: LanguageModelFeaturizer
  model_name: "roberta"
  model_weights: "roberta-base"
  cache_dir: "./cache_models"
- name: DIETClassifier
  epochs: 100
  batch_size: [16, 32]
  entity_recognition: True
  constraint_similarities: True
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100

policies:
- name: MemoizationPolicy
- name: RulePolicy
  priority: 5
  enable_fallback_prediction: false
- name: TEDPolicy
  priority: 10
  max_history: 5
  epochs: 100
assistant_id: 20250518-113815-tough-lily 